put default parameter for wake_interval into hiera
the reason for this is because if it's in the manifest, puppet converts
it to a string, which then makes it so it's a string in the yaml being
generated by datacat which causes the monitoring agent to fail to start
because it's trying to subtract something from a string, which doesn't
work:

```
  File
  "/usr/local/lib/python2.7/dist-packages/newrelic_plugin_agent/agent.py",
  line 127, in process
      self.next_wake_interval = self._wake_interval - duration
      TypeError: unsupported operand type(s) for -: 'str' and 'float'
```